### ISSUE TITLE
[Request] Load generated files back into generator

### ISSUE THREAD

**Issue by ForestedDev** [Silverfeelin/Starbound-ShopGenerator#2]
would it be possible for you to make it so we can load files back into the generator? could you also add support for directives? (such as what is generated by that hatter)

**Comment by Silverfeelin** [comment]
Been a while, almost forgot this project even existed!

I hope you're talking about the web generator, because I really don't feel like working on the other version. I'll add a simple import function where you can paste the item descriptor.

As for directives, you should be able to apply them by defining the `color` parameter on the output JSON. Doesn't really fit the scope of this project and I wouldn't be able to show the preview.

**Comment by Silverfeelin** [comment]
You can now import the descriptor with the new import option. 

![image](https://user-images.githubusercontent.com/17196309/79025418-f042d500-7b85-11ea-9e43-0fabfee50021.png)
